config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'sign_in', to: 'users/sessions#new'
    get 'sign_up', to: 'users/registrations#new'
    get 'forgot_password', to: 'users/passwords#new'
    get 'reset_password', to: 'users/passwords#edit'
  end

  resources :recipes, only: [:index] do
    collection do
      post :add_ingredient_to_session
      delete :remove_ingredient_from_session
    end
  end
  resources :ingredients, only: [:index]
  root to: 'recipes#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :recipes

  validates :name, presence: true, uniqueness: true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :recipe_ingredients
  has_many :recipes, through: :recipe_ingredients

  validates :name, presence: true, uniqueness: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients

  has_many :recipe_tags
  has_many :tags, through: :recipe_tags

  belongs_to :author, optional: true

  enum budget: [
    :bon_marché,
    :coût_moyen,
    :assez_cher
  ]
  enum difficulty: [
    :très_facile,
    :niveau_moyen,
    :facile,
    :difficile
  ]

  validates :name,            presence: true
  validates :prep_time,       numericality: { greater_than: 0 }
  validates :people_quantity, numericality: { greater_than: 0 }
  validates :cook_time,       numericality: { greater_than: 0 }
  validates :nb_comments,     numericality: { greater_than_or_equal_to: 0 }
  validates :rate,            numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 5 },
                              allow_nil: true

  def total_time
    prep_time + cook_time
  end

  def pretty_difficulty
    difficulty.gsub('_', ' ')
  end

  def pretty_budget
    budget.gsub('_', ' ')
  end
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient

  validates :recipe_id, uniqueness: { scope: :ingredient_id }
end

app/models/recipe_tag.rb
class RecipeTag < ApplicationRecord
  belongs_to :recipe
  belongs_to :tag

  validates :recipe_id, uniqueness: { scope: :tag_id }
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :recipe_tags
  has_many :recipes, through: :recipe_tags

  validates :name, presence: true, uniqueness: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackables
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def home; end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up)
    devise_parameter_sanitizer.permit(:account_update)
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def index
    ingredients = Ingredient.where("name like ?", "%#{params[:ingredient_name]}%")

    respond_to do |format|
      format.json { render json: ingredients, each_serializer: IngredientSerializer }
    end
  end
end

app/controllers/recipes_controller.rb
# frozen_string_literal: true

class RecipesController < ApplicationController
  def index
    unless (ingredients_names).empty?
      @recipes = FindRecipesByIngredients.new(ingredients_names).perform
    else
      @recipes = []
    end

    respond_to do |format|
      format.html
      format.json { render json: @recipes, each_serializer: RecipeSerializer }
    end
  end

  def add_ingredient_to_session
    session[:ingredients] ||= []
    session[:ingredients] << params[:ingredients_form][:ingredient_name]

    redirect_to :root
  end

  def remove_ingredient_from_session
    session[:ingredients].delete(params[:ingredient_name])

    redirect_to :root
  end

  private

  def ingredients_names
    session[:ingredients] || params[:ingredients_names] || []
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(_resource)
    root_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  def after_sign_in_path_for(_resource)
    root_path
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Pennylane Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/index.html.erb
<section class="m-5">
  <h1 class="text-center" >Welcome To Pennylane example</h1>

  <% unless (session[:ingredients] || []).empty? %>
    <table>
      <% session[:ingredients].each do |ingredient| %>
        <tr>
          <td><%= ingredient %></td>
          <td><%= link_to 'Remove Ingredient', remove_ingredient_from_session_recipes_path(ingredient_name: ingredient), method: :delete %></td>
        </tr>
      <% end %>
    </table>
  <% end %>

  <br>

  <%= form_for :ingredients_form, url: add_ingredient_to_session_recipes_path do |f| %>

    <%= f.text_field :ingredient_name, list: 'ingredients' %>

    <datalist id="ingredients">
      <% Ingredient.order(:name).pluck(:name).each do |ingredient_name| %>
        <option value="<%= ingredient_name %>"></option>
      <% end %>
    </datalist>

    <%= f.submit 'Add Ingredient' %>
  <% end %>

  <br>

  <% @recipes.each do |recipe| %>
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="row card-body">
            <img class="col-sm-12 col-md-3 col-lg-3 img-20"
                 src="<%= recipe.image_url || src="https://media.cntraveller.in/wp-content/uploads/2020/04/Home-cooking-recipes-self-isolatin-1366x768.jpg" %>"
            />
            <div class="col-sm-12 col-md-6 col-lg-6">
              <h5 class="card-title">
                <%= recipe.name %> <% recipe.author_tip ? "(#{recipe.author_tip})" : '' %>
                <br>
                <%= recipe.tags.pluck(:name).join(', ') %>.
              </h5>
              <p class="card-text">
                Author: <%= recipe.author.try(:name) %>,
                        total time: <%= distance_of_time_in_words(Time.now, Time.now + recipe.total_time) %>,
                        difficulty: <%= recipe.pretty_difficulty %>,
                        budget: <%= recipe.pretty_budget %>,
                        rate: <%= recipe.rate %>.
                <br>
                Ingredients: <%= recipe.description %>.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>

    <br>
  <% end %>
</section>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<section class="m-3 d-flex justify-content-between">
  <%- if controller_name != 'sessions' %>
    <%= link_to "Log in", new_session_path(resource_name) %>
  <% end %>

  <%- if devise_mapping.registerable? && controller_name != 'registrations' %>
    <%= link_to "Sign up", new_registration_path(resource_name) %>
  <% end %>

  <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
    <%= link_to "Forgot your password?", forgot_password_path(resource_name) %>
  <% end %>

  <%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
    <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %>
  <% end %>

  <%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
    <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %>
  <% end %>
</section>